export const CREATE_CHAMPIONSHIP = 'championship/CREATE_CHAMPIONSHIP';
export const CREATE_CHAMPIONSHIP_SUCCESS = 'championship/CREATE_CHAMPIONSHIP_SUCCESS';
export const CREATE_CHAMPIONSHIP_FAILED = 'championship/CREATE_CHAMPIONSHIP_FAILED';

export const GET_CHAMPIONSHIP = 'championship/GET_CHAMPIONSHIP';
export const GET_CHAMPIONSHIP_SUCCESS = 'championship/GET_CHAMPIONSHIP_SUCCESS';
export const GET_CHAMPIONSHIP_FAILED = 'championship/GET_CHAMPIONSHIP_FAILED';